# Generated by Django 4.2 on 2026-01-29 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('provider', models.CharField(choices=[('whatsapp_official', 'whatsapp_official'), ('evolution', 'evolution')], db_index=True, max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='tenants.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_channel_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('workspace', 'provider', 'external_id'), name='uniq_channel_external_per_workspace'),
        ),
    ]
