# Generated by Django 4.2 on 2026-01-31 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('evolution', 'evolution')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('provisioning', 'provisioning'), ('error', 'error')], db_index=True, default='provisioning', max_length=32)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_providers', to='tenants.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspaceprovider',
            constraint=models.UniqueConstraint(fields=('workspace', 'provider'), name='uniq_workspace_provider_per_workspace'),
        ),
    ]
