# Generated by Django 4.2 on 2026-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_workspaceprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
