# Generated by Django 4.2 on 2026-01-28 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
                ('raw_headers', models.JSONField(default=dict)),
                ('normalized', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
