# Generated by Django 4.2.28 on 2026-02-04 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=30)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('indexed', 'Indexed'), ('error', 'Error')], default='processing', max_length=20)),
                ('chunks_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='tenants.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.knowledgedocument')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='rag_knowled_documen_dc0905_idx')],
            },
        ),
    ]
